### ISSUE TITLE
Pas besoin de shebang

### ISSUE THREAD

**Issue by will-tam** [alevoski/decontamine_Linux#1]
Bonsoir.

Tu n'as pas besoin des shebangs `#!/usr/bin/python3` autre-part que dans le **main.py**, les autres fichiers étant des modules importés par main.py.

Il est vrai que j'ai vu des `if __name__ == '__main__':` à leur fin. Tu veux vraiment les faire exécuter en standalone ?

À plus.

**Comment by alevoski** [comment]
Salut,

J'ai fait ça pour me permettre de tester mes modules individuellement ;)

A plus !
