### ISSUE TITLE
open() function

### ISSUE THREAD

**Issue by alevoski** [alevoski/decontamine_Linux#3]
**open() function is used in some modules**
To avoid to forget to close the file, it's better to use with open() function.

**use with open()**
with open() automatically close the file.

**Comment by alevoski** [comment]
will-tam : commit e98f43a removed some ! Thanks ;)

**Comment by will-tam** [comment]
You can close, can't you ?

**Comment by alevoski** [comment]
Nope : there are 3 more in logManagement.py (lines 33, 47 & 53)

**Comment by alevoski** [comment]
Thanks, there are only 2 left : 
`33:        f = open(logFile, 'a', encoding=codec, errors='ignore')`
`54:                shutil.copyfileobj(open(i, 'r', errors='ignore', encoding='utf-8'), finalFile)`

**Comment by alevoski** [comment]
Ok, resolved with commit 46e3f70
