### ISSUE TITLE
No warn bug

### ISSUE THREAD

**Issue by will-tam** [alevoski/decontamine_Linux#8]
**Describe the bug**
If /home/decontamine doesn't exist, nothing warns us.

**To Reproduce**
Remove any /home/decontamine directory, and run program.

**Expected behavior**
A simple sentence to warns user, and stop program.

**Comment by alevoski** [comment]
Ok : init() in main.py module now verifies if the directory exists :

    # Verify if logDirectory exists
    if os.path.exists(logDirectory):
        # Clean log directory
        stats.cleanLog(logDirectory)
    else:
        print('ERROR !')
        print('You should create "/home/decontamine" directory to store the logs and the conf file !')
        exit(1)
